BookLibrary/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookLibrary.Models;
using BookLibrary.Services;
using BookLibrary.Models.ServiceModels.Amazon;
using System.Xml.Serialization;
using System.IO;
using BookLibrary.Functions.Core;
using System.Text.RegularExpressions;
using BookLibrary.Functions;
using BookLibrary.Models.ViewModels;
using Newtonsoft.Json;

namespace BookLibrary.Web.Controllers
{
    public class AlbumsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private Logger log = new Logger(typeof(AlbumsController));
        // GET: Albums
        public ActionResult Index()
        {
            //Albums.ApplySortTitle();
            int page = 1;
            if(!String.IsNullOrEmpty(Request.QueryString["p"]))
            {
                Int32.TryParse(Request.QueryString["p"], out page);
            }
            int perPage = Config.Get<Int32>("ItemsPerPage");
            int skip = (page - 1) * perPage;
            var albums = db.Albums.Include(a => a.Artist).OrderBy(a => a.SortTitle).Skip(skip).Take(perPage);
            List<PageLink> links = new List<PageLink>();
            links.Add(new PageLink("Recently Added", "/Albums/Recent"));
            if (User.Identity.IsAuthenticated)
            {
                links.Add(new PageLink("Add Album", "/Albums/Create"));
            }

            int albumCount = Albums.Count();
            double pageCount = Math.Ceiling((double)albumCount / (double)perPage);
            int start = page - 4;
            if(start < 1)
            {
                start = 1;
            }
            int end = page + 4;
            if(end > pageCount)
            {
                end = (int)pageCount;
            }

            List<string> pages = new List<string>();
            for(int idx = start; idx <= end; idx ++)
            {
                if (idx != page)
                {
                    pages.Add("<a href='/Albums?p=" + idx + "'>" + idx + "</a>&nbsp;");
                }
                else
                {
                    pages.Add("<strong>" + idx + "</strong>&nbsp;");
                }
            }

            ViewBag.CurrentPage = page;
            ViewBag.Pages = pages;
            ViewBag.TotalItems = albumCount;
            ViewBag.LinkList = links;
            return View(albums.ToList());
        }

        // GET: Albums/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Include(a => a.Artist).Include(a => a.TrackList).Where(a=>a.Id == id).FirstOrDefault();
            if (album == null)
            {
                return HttpNotFound();
            }
            if(album.NumberOfDiscs == 0)
            {
                album.NumberOfDiscs = Albums.DetermineDiscCountFromTracks(album.TrackList);
                album.ModifiedDate = DateTime.Now;
                db.Entry(album).State = EntityState.Modified;
                db.SaveChanges();
            }
            AlbumDetailViewModel albumDetailView = new AlbumDetailViewModel
            {
                Object = album,
                Offers = new Offers(),
                Reviews = new List<EditorialReview>(),
                SimilarProducts = new List<Album>(),
                NumberOfDiscs = 1,
                CategoryStreams = new List<List<Category>>()
            };
            ItemLookupResponse amzResponse;
            Exception ex;

            if (Core.ParseAmazonXml(album.AmazonResponse, out amzResponse, out ex))
            {
                albumDetailView.Offers = amzResponse.Items.Item.Offers;
                if (amzResponse.Items.Item.EditorialReviews != null)
                {
                    albumDetailView.Reviews = amzResponse.Items.Item.EditorialReviews.ToList();
                }
                if (amzResponse.Items.Item.SimilarProducts != null)
                {
                    foreach (SimilarProduct product in amzResponse.Items.Item.SimilarProducts)
                    {
                        Album similarAlbum = db.Albums.Where(a => a.ASIN == product.ASIN).FirstOrDefault();
                        if (similarAlbum != null)
                        {
                            albumDetailView.SimilarProducts.Add(similarAlbum);
                        }
                    }
                }
                if (amzResponse.Items.Item.Discs != null && amzResponse.Items.Item.Discs.Count() > 0)
                {
                    albumDetailView.NumberOfDiscs = amzResponse.Items.Item.Discs.Count();
                }
                else
                {
                    albumDetailView.NumberOfDiscs = 1;
                }
            }
            if (album.Artist.PersonId.HasValue)
            {
                Person person = People.PersonById(album.Artist.PersonId.Value);
                if (person.CelebrityId.HasValue)
                {
                    Celebrity celebrity;
                    if (!Artists.GetCelebrity(person.CelebrityId.Value, out celebrity, out ex))
                    {
                        return RedirectToAction("Index");
                    }
                    albumDetailView.ArtistDetail = celebrity;
                    string url_add = "";
                    if (Request.UserHostAddress.StartsWith("192.168.1."))
                    {
                        url_add = ":8081";
                    }
                    //links.Add(new PageLink("Artist Details", "http://celebritycentral.gmancoder.com" + url_add + "/Celebrities/Details/" + celebrity.Id, "_blank"));
                }
            }

            albumDetailView.CategoryStreams = Categories.DrawBreadcrumbsForObject(album.Id);
            string artistName = "";
            if (albumDetailView.Object.Artist.PersonId.HasValue)
            {
                artistName = albumDetailView.Object.Artist.Person.Name;
            }
            else
            {
                artistName = albumDetailView.Object.Artist.Name;
            }
            string details = "By <a href=\"/Artists/Details/" + albumDetailView.Object.Artist.Id + "\">" + artistName + "</a>; " + albumDetailView.Object.TrackList.Count() + " Tracks on " + albumDetailView.NumberOfDiscs + " Disc(s)";

            if (!String.IsNullOrEmpty(album.ReleaseDate))
            {
                details += "<br /><strong>Released: </strong>" + album.ReleaseDate;
            }
            ViewBag.SubTitle = details;
            List<PageLink> links = new List<PageLink>();
            links.Add(new PageLink("Album Information", album.Url, "_blank"));
            if(albumDetailView.ArtistDetail != null && !String.IsNullOrWhiteSpace(albumDetailView.ArtistDetail.Details))
            {
                links.Add(new PageLink("About the Artist", "#artist"));
            }
            if(albumDetailView.SimilarProducts.Count() > 0)
            {
                links.Add(new PageLink("Similar Items", "#similar"));
            }
            if(albumDetailView.Reviews.Count() > 0)
            {
                links.Add(new PageLink("Reviews", "#reviews"));
            }
            if(albumDetailView.Offers.TotalOffers > 0)
            {
                links.Add(new PageLink("Shopping Offers", "#shopping"));
            }
            if (User.Identity.IsAuthenticated)
            {
                links.Add(new PageLink("Add Track", "/Tracks/Create?album=" + album.Id));
                links.Add(new PageLink("Edit", "/Albums/Edit/" + album.Id));
                links.Add(new PageLink("Delete", "/Albums/Delete/" + album.Id, args: @"onClick=""return confirm('Are you sure?');"""));
            }
            ViewBag.LinkList = links;
            return View(albumDetailView);
        }

        [Authorize]
        // GET: Albums/Create
        public ActionResult Create()
        {
            Guid artistId = Guid.Empty;
            if(Request.QueryString["artist"] != null)
            {
                Guid.TryParse(Request.QueryString["artist"], out artistId);
            }
            ViewBag.ArtistId = new SelectList(Artists.GetAsObject(null), "Id", "Name", artistId);
            ViewBag.CategoryHtml = Categories.GetCategoryHtml(null);
            return View();
        }

        // POST: Albums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Album album)
        {
            log.Info("Create");
            log.Info(JsonConvert.SerializeObject(album));
            List<Guid> selectedCategories = new List<Guid>();
            try
            {
                bool amazon = false;
                bool noDiscs = false;
                Exception e;
                album.Id = Guid.NewGuid();
                album.CreatedDate = album.ModifiedDate = DateTime.Now;
                if(album.EntryType == "Amazon")
                {
                    if(Albums.AmazonAlbumExists(album.ASIN))
                    {
                        ModelState.AddModelError("ERR", "Album with ASIN '" + album.ASIN + "' already exists");
                        log.Error("Album with ASIN '" + album.ASIN + "' already exists");
                        ViewBag.ArtistId = new SelectList(Artists.GetAsObject(null), "Id", "Name", album.ArtistId);
                        ViewBag.Error = true;

BookLibrary/Views/Albums/Create.cshtml
@model BookLibrary.Models.Album

@{
    ViewBag.Title = "New Album";
    ViewBag.PageImage = "/Content/images/add_album.png";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "Albums", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EntryType, "Entry Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EntryType, new SelectList(
                    new[]
                    {
                        new { Value = "", Text = "" },
                        new { Value = "Amazon", Text = "Amazon" },
                        new { Value = "Manual", Text = "Manual" },
                    },
                    "Value",
                    "Text",
                    Model
                ), htmlAttributes: new { @class = "form-control", onChange = "EntryTypeChanged();" })
                @Html.ValidationMessageFor(model => model.EntryType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistId, "Artist", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArtistId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="entry_fields" id="amazon_entry_fields" style="display:none;">
            <div class="form-group">
                @Html.LabelFor(model => model.ASIN, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ASIN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ASIN, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="entry_fields" id="manual_entry_fields" style="display:none;">
            <div class="form-group">
                @Html.LabelFor(model => model.NumberOfDiscs, "Number of Discs", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NumberOfDiscs, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NumberOfDiscs, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UPC, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UPC, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UPC, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReleaseDate, "Release Date", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Binding, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Binding, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Binding, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageFileName, "Cover Image", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" id="ImageFileName" name="ImageFileName" class="form-control" />
                    @Html.ValidationMessageFor(model => model.ImageFileName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Url, "Detail Url", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label for="categoryTree" class="control-label col-md-2">Categories:</label>
                <input type="hidden" name="categoryTree" id="categoryTree" />
                <div class="col-md-10" id="category_tree">
                    
                    @Html.Raw(ViewBag.CategoryHtml)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}
@if (ViewBag.Error != null && ViewBag.Error)
{
    <script type="text/javascript">
        $(document).ready(function () {
            EntryTypeChanged();
        });
    </script>
}
<script type="text/javascript">
    $(document).ready(function () {
        $('#category_tree').on('changed.jstree', function (e, data) {
            var i, j, r = [];
            for (i = 0, j = data.selected.length; i < j; i++) {
                r.push(data.instance.get_node(data.selected[i]).a_attr.id);
            }
            $('#categoryTree').val(r.join(','));
        }).jstree({
            "core": {
                "multiple": true,
                'themes': { 'dots': false }
            },
            'plugins': ['changed', 'html_data'],

        });
    });
</script>

BookLibrary/Views/Albums/Edit.cshtml
@model BookLibrary.Models.Album

@{
    ViewBag.Title = "Update Album " + Model.Title;
    ViewBag.PageImage = "/Content/images/add_album.png";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "Albums", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EntryType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EntryType, new SelectList(
                    new[]
                    {
                        new { Value = "", Text = "" },
                        new { Value = "Amazon", Text = "Amazon" },
                        new { Value = "Manual", Text = "Manual" },
                    },
                    "Value",
                    "Text",
                    Model
                ), htmlAttributes: new { @class = "form-control", onChange = "EntryTypeChanged();" })
                @Html.ValidationMessageFor(model => model.EntryType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistId, "ArtistId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArtistId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="entry_fields" id="amazon_entry_fields" style="display:none;">
            <div class="form-group">
                @Html.LabelFor(model => model.ASIN, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ASIN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ASIN, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="entry_fields" id="manual_entry_fields" style="display:none;">
            <div class="form-group">
                @Html.LabelFor(model => model.NumberOfDiscs, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NumberOfDiscs, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NumberOfDiscs, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UPC, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UPC, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UPC, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Binding, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Binding, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Binding, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageFileName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" id="ImageFileName" name="ImageFileName" class="form-control" />
                    @Html.ValidationMessageFor(model => model.ImageFileName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label for="categoryTree" class="control-label col-md-2">Categories:</label>
                <div class="col-md-10" id="category_tree">
                    <input type="hidden" name="categoryTree" id="categoryTree" />
                    @Html.Raw(ViewBag.CategoryHtml)
                </div>
            </div>
        </div>
        @Html.HiddenFor(model => model.CreatedDate)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        EntryTypeChanged();
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#category_tree').on('select_node.jstree', function (e, data) {
            var id = data.node.a_attr.id
            var categoryTree = $('#categoryTree').val();
            if (categoryTree != "") {
                categoryTree += ",";
            }
            categoryTree += id;
        }).jstree({
            "core": {
                "multiple": true,
                'themes': { 'dots': false }
            },
            'plugins': ['changed', 'html_data'],

        });
    });
</script>


BookLibrary/Views/Albums/Index.cshtml
@model IEnumerable<BookLibrary.Models.Album>

@{
    ViewBag.Title = "All Albums";
    ViewBag.SubTitle = ViewBag.TotalItems + " Total Albums";
    ViewBag.PageImage = "/Content/Images/folder_music_icon.png";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{ int idx = 0; }
<div class="row">
    <div class="col-md-12 pull-right" style="text-align:right;">
        @foreach(string page in ViewBag.Pages)
        {
            @Html.Raw(page);
        }
    </div>
</div>
<div class="row">
    @foreach (var album in Model)
    {

        <div class="col-md-2" style="text-align:center;">
            <a href="/Albums/Details/@album.Id">
                <img src="~/Content/Images/albums/@album.ImageFileName" width="150" title="@album.Title" alt="@album.Title" /><br />
                @album.Title
            </a>
            <br />
            <span style="color:#999999;">By <a href="/Artists/Details/@album.ArtistId">@BookLibrary.Functions.Artists.GetArtistName(album.ArtistId)</a></span>
        </div>
        idx += 1;
        if (idx % 6 == 0)
        {
            @:</div><div class="row">
        }
    }
</div>
<div class="row">
    <div class="col-md-12 pull-right" style="text-align:right;">
        @foreach (string page in ViewBag.Pages)
        {
            @Html.Raw(page);
        }
    </div>
</div>

BookLibrary/Views/Albums/Recent.cshtml
@model BookLibrary.Models.ViewModels.RecentAlbumViewModel
@using BookLibrary.Models
@{
    ViewBag.Title = "Recently Added Albums";
    ViewBag.SubTitle = ViewBag.TotalItems + " Total Albums";
    ViewBag.PageImage = "/Content/Images/folder_music_icon.png";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12 pull-right" style="text-align:right;">
        @foreach (string page in ViewBag.Pages)
        {
            @Html.Raw(page);
        }
    </div>
</div>
@if(Model.Today.Count() > 0)
{
    <h3><strong>Today</strong></h3>
    int idx = 0;
    <div class="row">
        @foreach (var album in Model.Today)
        {

            <div class="col-md-2" style="text-align:center;">
                <a href="/Albums/Details/@album.Id">
                    <img src="~/Content/Images/albums/@album.ImageFileName" width="150" title="@album.Title" alt="@album.Title" /><br />
                    @album.Title<
                </a>
                <br />
                <span style="color:#999999;">By <a href="/Artists/Details/@album.ArtistId">@album.Artist.Name</a></span>
            </div>
            idx += 1;
            if (idx % 6 == 0)
            {
                @:</div><div class="row">
            }
        }
    </div>
}
@if (Model.Yesterday.Count() > 0)
{
    <h3><strong>Yesterday</strong></h3>
    int idx = 0;
    <div class="row">
        @foreach (var album in Model.Yesterday)
        {

            <div class="col-md-2" style="text-align:center;">
                <a href="/Albums/Details/@album.Id">
                    <img src="~/Content/Images/albums/@album.ImageFileName" width="150" title="@album.Title" alt="@album.Title" /><br />
                    @album.Title
                </a>
                <br />
                <span style="color:#999999;">By <a href="/Artists/Details/@album.ArtistId">@album.Artist.Name</a></span>
            </div>
            idx += 1;
            if (idx % 6 == 0)
            {
                @:</div><div class="row">
            }
        }
    </div>
}
@if (Model.ThisWeek.Count() > 0)
{
    <h3><strong>This Week</strong></h3>
    int idx = 0;
    <div class="row">
        @foreach (var album in Model.ThisWeek)
        {

            <div class="col-md-2" style="text-align:center;">
                <a href="/Albums/Details/@album.Id">
                    <img src="~/Content/Images/albums/@album.ImageFileName" width="150" title="@album.Title" alt="@album.Title" /><br />
                    @album.Title
                </a>
                <br />
                <span style="color:#999999;">By <a href="/Artists/Details/@album.ArtistId">@album.Artist.Name</a></span>
            </div>
            idx += 1;
            if (idx % 6 == 0)
            {
                @:</div><div class="row">
            }
        }
    </div>
}
@if (Model.LastWeek.Count() > 0)
{
    <h3><strong>Last Week</strong></h3>
    int idx = 0;
    <div class="row">
        @foreach (var album in Model.LastWeek)
        {

            <div class="col-md-2" style="text-align:center;">
                <a href="/Albums/Details/@album.Id">
                    <img src="~/Content/Images/albums/@album.ImageFileName" width="150" title="@album.Title" alt="@album.Title" /><br />
                    @album.Title
                </a>
                <br />
                <span style="color:#999999;">By <a href="/Artists/Details/@album.ArtistId">@album.Artist.Name</a></span>
            </div>
            idx += 1;
            if (idx % 6 == 0)
            {
                @:</div><div class="row">
            }
        }
    </div>
}
@if(Model.Older.Count() > 0)
{
    foreach(KeyValuePair<int, List<Album>> year in Model.Older)
    {
        <h3><strong>@year.Key</strong></h3>
        int idx = 0;
        <div class="row">
            @foreach (var album in year.Value)
            {

                <div class="col-md-2" style="text-align:center;">
                    <a href="/Albums/Details/@album.Id">
                        <img src="~/Content/Images/albums/@album.ImageFileName" width="150" title="@album.Title" alt="@album.Title" /><br />
                        @album.Title
                    </a>
                    <br />
                    <span style="color:#999999;">By <a href="/Artists/Details/@album.ArtistId">@album.Artist.Name</a></span>
                </div>
                idx += 1;
                if (idx % 6 == 0)
                {
                    @:</div><div class="row">
                }
            }
        </div>
    }
}
<div class="row">
    <div class="col-md-12 pull-right" style="text-align:right;">
        @foreach (string page in ViewBag.Pages)
        {
            @Html.Raw(page);
        }
    </div>
</div>