BookLibrary/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookLibrary.Models;
using BookLibrary.Functions;
using System.IO;
using BookLibrary.Functions.Core;
using BookLibrary.Models.ViewModels;
using BookLibrary.Services;
using Newtonsoft.Json;

namespace BookLibrary.Web.Controllers
{
    public class ArtistsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private Logger log = new Logger(typeof(ArtistsController));
        // GET: Artists
        public ActionResult Index()
        {
            //Artists.ApplySortName();
            //Artists.MergeToPeople();
            int page = 1;
            if (!String.IsNullOrEmpty(Request.QueryString["p"]))
            {
                Int32.TryParse(Request.QueryString["p"], out page);
            }
            int perPage = Config.Get<Int32>("ItemsPerPage");
            int skip = (page - 1) * perPage;
            if (User.Identity.IsAuthenticated)
            {
                List<PageLink> links = new List<PageLink>();
                links.Add(new PageLink("Add Artist", "/Artists/Create"));
                ViewBag.LinkList = links;
            }
            int artistCount = Artists.Count();
            double pageCount = Math.Ceiling((double)artistCount / (double)perPage);
            int start = page - 4;
            if (start < 1)
            {
                start = 1;
            }
            int end = page + 4;
            if (end > pageCount)
            {
                end = (int)pageCount;
            }

            List<string> pages = new List<string>();
            for (int idx = start; idx <= end; idx++)
            {
                if (idx != page)
                {
                    pages.Add("<a href='/Artists?p=" + idx + "'>" + idx + "</a>&nbsp;");
                }
                else
                {
                    pages.Add("<strong>" + idx + "</strong>&nbsp;");
                }
            }

            ViewBag.CurrentPage = page;
            ViewBag.Pages = pages;
            ViewBag.TotalItems = artistCount;

            List<Artist> allArtists = db.Artists.Include(a => a.Person).ToList();
            List<LibraryObject> artistsView = new List<LibraryObject>();
            foreach(Artist artist in allArtists)
            {
                LibraryObject newObject = new LibraryObject();
                newObject.Id = artist.Id;
                if(artist.PersonId.HasValue)
                {
                    newObject.Name = artist.Person.Name;
                    newObject.Image = artist.Person.DisplayImage;
                    newObject.SortName = artist.Person.SortName;
                }
                else
                {
                    newObject.Name = artist.Name;
                    newObject.Image = artist.DisplayImage;
                    newObject.SortName = artist.SortName;
                }
                artistsView.Add(newObject);
            }

            return View(artistsView.OrderBy(o => o.SortName).Skip(skip).Take(perPage).ToList());

        }

        // GET: Artists/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artists.Include(a=>a.Person).Include(a => a.AssociatedArtists).Where(a => a.Id == id).FirstOrDefault();
            
            if (artist == null)
            {
                return HttpNotFound();
            }
            List<PageLink> links = new List<PageLink>();
            PersonViewModel viewModel;
            Exception ex;
            string view = "PeopleDetails";
            if (artist.IsGroup)
            {
                view = "Details";
                ArtistViewModel artistView = new ArtistViewModel
                {
                    Artist = artist,
                    Albums = db.Albums.Where(a => a.ArtistId == artist.Id).OrderBy(a => a.Title).ToList(),
                    AssociatedArtists = new List<LibraryObject>()
                };
                try
                {
                    artistView.NonAlbumTracks = Tracks.GetNonAlbumTracksForArtist(artist.Id);
                }
                catch
                {
                    artistView.NonAlbumTracks = new List<Track>();
                }
                
                if (artistView.Artist.AssociatedArtists.Count() > 0)
                {
                    links.Add(new PageLink("Associated Artists", "#associatedArtists"));
                    foreach (Artist assocArtist in artist.AssociatedArtists)
                    {
                        artistView.AssociatedArtists.Add(Artists.AsObject(assocArtist));
                    }
                }
                if (artistView.Albums.Count() > 0)
                {
                    links.Add(new PageLink("Albums", "#albums"));
                }
                if (artistView.NonAlbumTracks.Count() > 0)
                {
                    links.Add(new PageLink("Tracks on Other Albums", "#tracks"));
                }
                AppendUserActions(ref links, artist);
                ViewBag.LinkList = links;
                return View(view, artistView);
            }
            else
            {
                if (!People.GeneratePersonView(id.Value, "Artist", out viewModel, out ex))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
                }

                People.DrawLinkListForView(viewModel, "Artist", ref links);
                AppendUserActions(ref links, artist);
                ViewBag.LinkList = links;
                return View(view, viewModel);
            }
        }

        private void AppendUserActions(ref List<PageLink> links, Artist artist)
        {
            if (User.Identity.IsAuthenticated)
            {
                links.Add(new PageLink("Add Album", "/Albums/Create?artist=" + artist.Id));
                if (artist.IsGroup)
                {
                    links.Add(new PageLink("Add Associated Artist(s)", "/Artists/AddAssociated/" + artist.Id));
                }
                links.Add(new PageLink("Edit", "/Artists/Edit/" + artist.Id));
                links.Add(new PageLink("Delete", "/Artists/Delete/" + artist.Id, args: @"onClick=""return confirm('Are you sure?');"""));
            }
        }

        [Authorize]
        // GET: Artists/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Artists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Artist artist)
        {
            log.Info("Create");
            log.Info(JsonConvert.SerializeObject(artist));
            Exception ex;
            if (ModelState.IsValid)
            {
                string Name = Request.Form["Name"];
                if (!String.IsNullOrEmpty(Name))
                {
                    if ((artist.IsGroup && Artists.GroupExists(Name)) || (!artist.IsGroup && Artists.ArtistExists(Name)))
                    {
                        ModelState.AddModelError("ERR", "Artist " + artist.Name + " already exists");
                        log.Error("Artist " + artist.Name + " already exists");
                        return View(artist);
                    }
                    artist.Id = Guid.NewGuid();
                    artist.CreatedDate = DateTime.Now;

                    if (!UpdateArtist(ref artist, Name, out ex))
                    {
                        ModelState.AddModelError("ERR", ex.Message);
                        log.Error("Error", ex);
                        return View(artist);
                    }

                    db.Artists.Add(artist);
                    db.SaveChanges();
                    return RedirectToAction("Details", new { id = artist.Id });
                }
                ModelState.AddModelError("ERR", "Name Required");
            }

            return View(artist);
        }

        [Authorize]
        // GET: Artists/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artists.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // POST: Artists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Artist artist)
        {
            log.Info("Edit");
            log.Info(JsonConvert.SerializeObject(artist));
            Exception ex;
            if (ModelState.IsValid)
            {
                string Name = Request.Form["Name"];
                if (!String.IsNullOrEmpty(Name))
                {
                    if (!UpdateArtist(ref artist, Name, out ex))
                    {
                        ModelState.AddModelError("ERR", ex.Message);
                        log.Error("Error", ex);
                        return View(artist);
                    }

BookLibrary/Views/Artists/AddAssociated.cshtml
@model BookLibrary.Models.Artist

@{
    ViewBag.Title = "Update Associated Artists";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("UpdateAssociated", "Artists", new { Id = Model.Id }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        @foreach (var item in Model.AssociatedArtists)
        {
            <div class="col-md-2 associated-artist" style="text-align:center;" id="@item.Id">
                <input type="hidden" name="artist_id[]" id="artist_id_@item.Id" value="@item.Id" />
                <img src="@item.Person.DisplayImage" width="150" title="@item.Person.Name" alt="@item.Person.Name" /><br />
                @item.Person.Name<br />
                <a href="javascript:;" onclick="RemoveAssociatedArtist('@item.Id');">Remove</a>
            </div>
        }
        <div class="col-md-2 associated-artist" style="text-align:center;" id="associated-add-button">
            <a href="javascript:;" onclick="AddAssociatedArtist();" class="btn btn-success">Add New</a>
            <a href="javascript:;" onclick="$(this).parent().parent().parent().submit()" class="btn btn-primary">Complete Update</a>
        </div>
    </div>
}
<div class="modal fade" id="associatedArtistModal" tabindex="-1" role="dialog" aria-labelledby="associatedArtistModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="max-height:90%;overflow:auto;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="associatedArtistModalLabel">Select Associated Artist</h4>
            </div>
            <div class="modal-body">
                <div id="associatedArtist_modal_loading" style="display:none;">
                    <img src="~/Content/Images/ajax-loader.gif" alt="Loading" />
                </div>
                <div id="associatedArtist_modal_content">
                    <div class="row">
                        <div class="col-md-12">
                            <strong>Get Artists Starting With:</strong>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <a href="javascript:;" onclick="GetAssociatedArtists('A');">A</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('B');">B</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('C');">C</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('D');">D</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('E');">E</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('F');">F</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('G');">G</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('H');">H</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('I');">I</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('J');">J</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('K');">K</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('L');">L</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('M');">M</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('N');">N</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('O');">O</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('P');">P</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('Q');">Q</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('R');">R</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('S');">S</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('T');">T</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('U');">U</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('V');">V</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('W');">W</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('X');">X</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('Y');">Y</a>&nbsp;
                            <a href="javascript:;" onclick="GetAssociatedArtists('Z');">Z</a>&nbsp;
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12" id="associatedArtists">

                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

BookLibrary/Views/Artists/Create.cshtml
@model BookLibrary.Models.Artist

@{
    ViewBag.Title = "Add Artist";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.PageImage = "/Content/images/add_artist_user.png";
}

@using (Html.BeginForm("Create", "Artists", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model=>model.IsGroup, "Is Group", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-10" id="is_group_field">
                @Html.DropDownListFor(model => model.IsGroup, new SelectList(
                    new[]
                    {
                        new { Value = "", Text = "" },
                        new { Value = "false", Text = "No" },
                        new { Value = "true", Text = "Yes" },
                    },
                    "Value",
                    "Text",
                    Model
                ), htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Name", new { @class = "control-label col-lg-2"})
            <div class="col-md-10">
                @Html.TextBox("Name", null, new { @class = "form-control", required = "required" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("DisplayImage", "Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="ArtistDisplayImage" name="ArtistDisplayImage" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", null, htmlAttributes: new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}


BookLibrary/Views/Artists/Details.cshtml

@model BookLibrary.Models.ViewModels.ArtistViewModel
@using BookLibrary.Models
@{
    ViewBag.Title = Model.Artist.Name;
    ViewBag.SubTitle = Html.Raw(Model.Albums.Count() + " Total Albums");
    ViewBag.PageImage = Model.Artist.DisplayImage;
    if (Model.Celebrity != null)
    {
        ViewBag.Details = Model.Celebrity.Details;
    }
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Model.AssociatedArtists.Count() > 0)
{
    <a id="associatedArtists" name="associatedArtists"></a>
    <h4>Artists Associated With @Model.Artist.Name</h4>
     int idx = 0;
    <div class="row">
        @foreach (var item in Model.AssociatedArtists.OrderBy(a => a.SortName))
        {
            <div class="col-md-2" style="text-align:center;">
                <a href="/Artists/Details/@item.Id">
                    <img src="@item.Image" width="150" title="@item.Name" alt="@item.Name" /><br />
                    @item.Name
                </a>
            </div>
            idx += 1;
            if (idx % 6 == 0)
            {
                @:</div><div class="row">
            }
        }
    </div>
}
@if (Model.Albums.Count() > 0)
{
    <a id="albums" name="albums"></a>
    <h4>@Model.Artist.Name's Albums</h4>
    int idx = 0;
    <div class="row">
        @foreach (Album album in Model.Albums)
        {
            <div class="col-md-2" style="text-align:center;">
                <a href="/Albums/Details/@album.Id">
                    <img src="~/Content/Images/albums/@album.ImageFileName" width="150" title="@album.Title" alt="@album.Title" /><br />
                    @album.Title
                </a>
            </div>
            idx += 1;
            if (idx % 6 == 0)
            {
                @:</div><div class="row">
            }
        }
    </div>
}
@if (Model.NonAlbumTracks.Count() > 0)
{
    <a id="tracks" name="tracks"></a>
    <h4>Tracks by @Model.Artist.Name on other albums</h4>
    int idx = 0;
    <div class="row">
        @foreach (Track track in Model.NonAlbumTracks)
        {
            <div class="col-md-2" style="text-align:center;">
                <img src="~/Content/Images/albums/@track.Album.ImageFileName" width="150" title="@track.Album.Title" alt="@track.Album.Title" /><br />
                <a href="/Tracks/Details/@track.Id">@track.Name</a> on <a href="/Albums/Details/@track.Album.Id">@track.Album.Title </a>
            </div>
            idx += 1;
            if (idx % 6 == 0)
            {
                @:</div><div class="row">
            }
        }
        
    </div>
}


BookLibrary/Views/Artists/Edit.cshtml
@model BookLibrary.Models.Artist

@{

    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Model.IsGroup)
    {
        ViewBag.Title = "Update " + Model.Name;
        ViewBag.PageImage = Model.DisplayImage;
    }
    else
    {
        ViewBag.Title = "Update " + Model.Person.Name;
        ViewBag.PageImage = Model.Person.DisplayImage;
    }
}

@using (Html.BeginForm("Edit", "Artists", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IsGroup, "Is Group", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-10" id="is_group_field">
                @Html.DropDownListFor(model => model.IsGroup, new SelectList(
                    new[]
                    {
                        new { Value = "", Text = "" },
                        new { Value = "false", Text = "No" },
                        new { Value = "true", Text = "Yes" },
                    },
                    "Value",
                    "Text",
                    Model
                ), htmlAttributes: new { @class = "form-control", onChange = "IsGroupChanged(true);" })
            </div>
            <div class="col-lg-1" id="celebrity_refresh_button" style="display:none;">
                <a href="javascript:;" onclick="ShowCelebritySelection('A');" class="btn btn-success">Select Celebrity</a>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Name", new { @class = "control-label col-lg-2" })
            <div class="col-md-10">
                @Html.TextBox("Name", null, new { @class = "form-control", required = "required" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("DisplayImage", "Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="ArtistDisplayImage" name="ArtistDisplayImage" class="form-control" />
            </div>
        </div>
        @Html.HiddenFor(model => model.CreatedDate)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", null, htmlAttributes: new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}
<script type="text/javascript">
        $(document).ready(function () {
            IsGroupChanged(false);
        });
</script>

BookLibrary/Views/Artists/Index.cshtml
@model IEnumerable<BookLibrary.Models.ViewModels.LibraryObject>

@{
    ViewBag.Title = "All Artists";
    ViewBag.SubTitle = ViewBag.TotalItems + " Total";
    ViewBag.PageImage = "/Content/images/artists.png";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12 pull-right" style="text-align:right;">
        @foreach (string page in ViewBag.Pages)
        {
            @Html.Raw(page);
        }
    </div>
</div>
@{ int idx = 0; }
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-2" style="text-align:center;">
            <a href="/Artists/Details/@item.Id">
                <img src="@item.Image" width="150" title="@item.Name" alt="@item.Name" /><br />
                @item.Name
            </a>
        </div>
        idx += 1;
        if (idx % 6 == 0)
        {
            @:</div><div class="row">
            }
    }
</div>
<div class="row">
    <div class="col-md-12 pull-right" style="text-align:right;">
        @foreach (string page in ViewBag.Pages)
        {
            @Html.Raw(page);
        }
    </div>
</div>